# templates/secret.yaml
{{- if .Values.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-key
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc }}
{{- end }}